# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
      options = [ "defaults" "size=25%" "mode=755" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/0a9835ef-4865-4ffb-84f9-1462d7da4477";

  fileSystems."/persist" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/persist/persist/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/root/.local/share/nix" =
    { device = "/persist/persist/root/.local/share/nix";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/root/.ssh" =
    { device = "/persist/persist/root/.ssh";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/NetworkManager" =
    { device = "/persist/persist/var/lib/NetworkManager";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/nixos" =
    { device = "/persist/persist/var/lib/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/systemd/coredump" =
    { device = "/persist/persist/var/lib/systemd/coredump";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/log" =
    { device = "/persist/persist/var/log";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/swap" =
    { device = "/dev/mapper/crypted";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8E31-39F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
